name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug Network
      run: |
        ping -c 4 mobilespac.com
        nslookup mobilespac.com

    - name: Add SSH known hosts
      run: |
        ssh-keyscan mobilespac.com >> ~/.ssh/known_hosts
      continue-on-error: true

    - name: Test SSH connection
      if: success()
      run: ssh -vT mobilesp@mobilespac.com 'echo "SSH connection successful"'

    - name: Deploy
      if: success()
      run: |
        # Your deployment script here
        ssh mobilesp@mobilespac.com 'your-deployment-command'

