name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -l ~/.ssh
        cat ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH known hosts
      run: ssh-keyscan example.com >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -v user@example.com 'echo "SSH connection successful"'

    - name: Deploy
      run: |
        # Your deployment script here
        ssh user@example.com 'your-deployment-command'
